### ISSUE TITLE
Some URL blocking rules are not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForiOS#1139]
Original report: https://github.com/AdguardTeam/AdguardFilters/issues/35815

### Steps to reproduce

1. Go to https://www.reuters.com/article/us-mideast-iran-usa/trump-threatens-obliteration-iran-calls-white-house-mentally-retarded-idUSKCN1TQ0V5

### Expected behavior

Ad on screenshot is blocked

<details>

![image](https://user-images.githubusercontent.com/8361299/61592217-ee407c80-abd8-11e9-8986-bc70fffa2757.png)

</details>

### Actual behavior

Ad is not blocked.

This ad must be blocked by the rule from Base filter - `||dianomi.com^$third-party`
This rule exists in optimized version of filter:
https://filters.adtidy.org/ios/filters/2_optimized.txt
It does not applied even in user filter.

### Your environment

* Device model and storage size: iPad
* Operating system and version: iOS 12.3.1
* Safari)
* Wi-fi

**Comment by ameshkov** [comment]
@Alex-302 can you reproduce it on desktop with AG for Safari?

**Comment by 08kovalchuk03** [comment]
@Alex-302 could you provide logs?
I've tried to reproduce this bug, but didn't successeed
I've copied and added filters from this link https://filters.adtidy.org/ios/filters/2_optimized.txt
And they've successfully blocked all the ads on this site

![Simulator Screen Shot - iPhone Xs Max - 2019-08-09 at 10 56 41](https://user-images.githubusercontent.com/52201516/62763507-655c8880-ba94-11e9-8c51-984ee7926088.png)

**Comment by Superkloton** [comment]
Yes seems to work now. I reported this problem initially but it doesn't seem to exist anymore.

**Comment by Alex-302** [comment]
Still can reproduce this issue.

**Comment by Alex-302** [comment]
Logs: [adguardforios_logs_235082019188.zip](https://github.com/AdguardTeam/AdguardForiOS/files/3535227/adguardforios_logs_235082019188.zip)

**Comment by Superkloton** [comment]
Yes it's back. Very strange.

**Comment by 08kovalchuk03** [comment]
ruleId of every filter is zero, this was fixed with affinity task
https://github.com/AdguardTeam/AdguardForiOS/issues/1104

**Comment by Alex-302** [comment]
@08kovalchuk03 so `dianomi.com` must be blocked in 3.1(190)? I still see that ad.

**Comment by 08kovalchuk03** [comment]
@Alex-302 I've tested this filter with browser extension and the result is the same 
It doesn't block dianomi content
<img width="1359" alt="Снимок экрана 2019-08-27 в 16 37 50" src="https://user-images.githubusercontent.com/52201516/63775957-1ebabb00-c8e9-11e9-83fe-2cf152589cb3.png">

**Comment by SoLenny** [comment]
It seems like the problem is really in the filter. Advertisement still showing.
https://uploads.adguard.com/solennyy9ryq.png
https://uploads.adguard.com/solenny6g7v8.png

**Comment by Alex-302** [comment]
@SoLenny filter contains required rule. You can check it in custom filter.
@08kovalchuk03 is is blocked by Base filter in Chrome
![image](https://user-images.githubusercontent.com/8361299/64127123-2252b400-cdb9-11e9-9fe1-d40066a77df3.png)

**Comment by Alex-302** [comment]
UPD: ads are loaded by inline script. Fixed this issue.
But `dianomi.com` requests still not blocked.
