### ISSUE TITLE
Infinite filter updates on iOS 17 

### ISSUE THREAD

**Issue by AidanGee7** [AdguardTeam/AdguardForiOS#2188]
### Issue Details

- **AdGuard version:**
  - AdGuard for iOS 4.5.0 (1002)
- **Device model and storage size:**
  - iPhone 13 Pro Max (256GB)
- **Operating system and version:**
  - iOS 17 Beta 3
- **Browser or App:**
  - iOS App

### Expected Behavior

Should be able to enable Safari protection and refresh/update filters like normal.

### Actual Behavior

Despite having everything enabled, the Safari protection fails to enable correctly. Trying to update the filters results in either; a never ending "updating" message, a "filter update error", or a "SFErrorDomain 3" popup message.

### Screenshots

<details><summary>Screen recording:</summary>

Attached video:
https://github.com/AdguardTeam/AdguardForiOS/assets/28673281/c609f7ce-30cc-4da9-bbe0-a7553e8c691e

</details>

### Additional Information

The screen recording shows:

- All extension options enabled.
- Safari protection enabled in-app
- All filters enabled
- Advanced protection enabled in Safari
- AdGuard test page not detecting AdGuard
- Update of filters failing with error message

Only started happening in latest iOS update/AdGuard update (not sure exactly which is causing the issue). I'm getting the same "SFErrorDomain 3" when I try an AdGuard alternative too (1Blocker).

I've tried disabling DNS protection, enabling/disabling different filters, uninstalling/reinstalling the app, rebooting phone etc - All with no luck.

Might not be the only one - https://www.reddit.com/r/iOSBeta/comments/14rh2x1/comment/jqzdj53/?utm_source=reddit&utm_medium=web2x&context=3

Probably just an iOS beta bug but thought I’d raise it in case they’ve changed something permanently in the back end!

Please let me know if you need anymore info/logs!

**Comment by fulkaffe** [comment]
> ### Issue Details
> * **AdGuard version:**
>   
>   * AdGuard for iOS 4.5.0 (1002)
> * **Device model and storage size:**
>   
>   * iPhone 13 Pro Max (256GB)
> * **Operating system and version:**
>   
>   * iOS 17 Beta 3
> * **Browser or App:**
>   
>   * iOS App
> 
> ### Expected Behavior
> Should be able to enable Safari protection and refresh/update filters like normal.
> 
> ### Actual Behavior
> Despite having everything enabled, the Safari protection fails to enable correctly. Trying to update the filters results in either; a never ending "updating" message, a "filter update error", or a "SFErrorDomain 3" popup message.
> 
> ### Screenshots
> Screen recording:
> ### Additional Information
> The screen recording shows:
> 
> * All extension options enabled.
> * Safari protection enabled in-app
> * All filters enabled
> * Advanced protection enabled in Safari
> * AdGuard test page not detecting AdGuard
> * Update of filters failing with error message
> 
> Only started happening in latest iOS update/AdGuard update (not sure exactly which is causing the issue). I'm getting the same "SFErrorDomain 3" when I try an AdGuard alternative too (1Blocker).
> 
> I've tried disabling DNS protection, enabling/disabling different filters, uninstalling/reinstalling the app, rebooting phone etc - All with no luck.
> 
> Might not be the only one - https://www.reddit.com/r/iOSBeta/comments/14rh2x1/comment/jqzdj53/?utm_source=reddit&utm_medium=web2x&context=3
> 
> Probably just an iOS beta bug but thought I’d raise it in case they’ve changed something permanently in the back end!
> 
> Please let me know if you need anymore info/logs!

Same for me. Also on beta 3.

**Comment by finegorko** [comment]
same :/

**Comment by fobin** [comment]
Same

**Comment by AidanGee7** [comment]
Just managed to capture the "SFErrorDomain Error 3" message too:

![IMG_5909](https://github.com/AdguardTeam/AdguardForiOS/assets/28673281/6bd62003-7666-4c06-8e8d-b7e3e2f85062)

**Comment by qiyelishang** [comment]
Same

**Comment by raditol** [comment]
Not working on Beta 3 :/ I think it’s working after reinstalling but as soon I touch the settings it stopped

**Comment by raditol** [comment]
So, for all current beta users here is a quick fix:

(That works for me Ios 17 B3)

Reinstall AdGuard 

Start DNS Protection 
Choose AdGuard DNS

In Split Tunnel Mode it’s working even if apple iCloud privat relay is on 

https://d3ward.github.io/toolz/adblock.html

(Test bench) 

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/73539229/f10f33be-e8fc-46d1-944f-7c7599504b7c)

**Comment by maxikuzmin** [comment]
@AidanGee7 thank you! We are aware of this problem. We are already in the process of fixing the update issue. This should be fixed in the upcoming 4.6 update

About Safari protection we know, it seems that the problem is due to an ios update. We are waiting for the next beta 4, hopefully it will be fixed.

@raditol thank you! It really helps as a temporary solution. DNS filtering blocks ads in Safari. FYI @fulkaffe @finegorko @fobin @PavelParkhomenko @qiyelishang

**Comment by fobin** [comment]
Beta 4 quickly tested. It doesn't seem to resolve this issue.

**Comment by Rukario** [comment]
> Beta 4 quickly tested. It doesn't seem to resolve this issue.

Same, Adguard is still no go for beta 4

We've been on beta 3 for 3 weeks, have had enough with this bug and beta 4 is one sad update with literally nothing positive changes so far, all bugs of beta 3 remain. Let's see what's coming for this beta 5 but should AdGuard have a temporary solution for this bug meantime?

**Comment by AidanGee7** [comment]
Still not working for me either on beta 4 :(

However, as a bit of a workaround - I've been able to get cosmetic blocking/filtering working by using smaller, more "optimised" filters. It appears to break whenever you try and use a larger list for some reason.

If this helps anyone else, I'm able to update (and enable) these filters together:

- AdGuard Mobile Ads Filters (One of the defaults)
- AdGuard Social Media filter (One of the defaults)
- EasyList (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt
- AdGuard Annoyances filter (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt

If I try to enable any other lists/larger lists it starts to error out and not work correctly. But using these seems to block 99% of ads/cookie notices etc. Combined with DNS protection, the protection level is almost back to where it was before beta 3.

Feel free to have a play with different filters and let me know how it works for you!

**Comment by AllForLandlord** [comment]
> Still not working for me either on beta 4 :(
> 
> However, as a bit of a workaround - I've been able to get cosmetic blocking/filtering working by using smaller, more "optimised" filters. It appears to break whenever you try and use a larger list for some reason.
> 
> If this helps anyone else, I'm able to update (and enable) these filters together:
> 
> * AdGuard Mobile Ads Filters (One of the defaults)
> * AdGuard Social Media filter (One of the defaults)
> * EasyList (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt
> * AdGuard Annoyances filter (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt
> 
> If I try to enable any other lists/larger lists it starts to error out and not work correctly. But using these seems to block 99% of ads/cookie notices etc. Combined with DNS protection, the protection level is almost back to where it was before beta 3.
> 
> Feel free to have a play with different filters and let me know how it works for you!
> 
> Hopefully Apple fixes this soon so we won't have to worry about doing any of this!

Thank you so much! It works so perfectly!

**Comment by SubElement** [comment]
> Still not working for me either on beta 4 :(
> 
> However, as a bit of a workaround - I've been able to get cosmetic blocking/filtering working by using smaller, more "optimised" filters. It appears to break whenever you try and use a larger list for some reason.
> 
> If this helps anyone else, I'm able to update (and enable) these filters together:
> 
> * AdGuard Mobile Ads Filters (One of the defaults)
> * AdGuard Social Media filter (One of the defaults)
> * EasyList (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt
> * AdGuard Annoyances filter (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt
> 
> If I try to enable any other lists/larger lists it starts to error out and not work correctly. But using these seems to block 99% of ads/cookie notices etc. Combined with DNS protection, the protection level is almost back to where it was before beta 3.
> 
> Feel free to have a play with different filters and let me know how it works for you!
> 
> Hopefully Apple fixes this soon so we won't have to worry about doing any of this!

Legend! This works like a dream until this is fixed! Thank you!

**Comment by Rukario** [comment]
Unfortunately, it looks like this workaround is behind one of the paid features we can't have access to without paying up.

**Comment by fulkaffe** [comment]
> Still not working for me either on beta 4 :(
> 
> However, as a bit of a workaround - I've been able to get cosmetic blocking/filtering working by using smaller, more "optimised" filters. It appears to break whenever you try and use a larger list for some reason.
> 
> If this helps anyone else, I'm able to update (and enable) these filters together:
> 
> * AdGuard Mobile Ads Filters (One of the defaults)
> * AdGuard Social Media filter (One of the defaults)
> * EasyList (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt
> * AdGuard Annoyances filter (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt
> 
> If I try to enable any other lists/larger lists it starts to error out and not work correctly. But using these seems to block 99% of ads/cookie notices etc. Combined with DNS protection, the protection level is almost back to where it was before beta 3.
> 
> Feel free to have a play with different filters and let me know how it works for you!
> 
> Hopefully Apple fixes this soon so we won't have to worry about doing any of this!

Thank you for this 😀🥹🥳

**Comment by dnmTX** [comment]
> AdGuard Annoyances filter (Optimized) - From here - https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt

Just FYI.This is the same as the built in **AdGuard Annoyances filter**:
https://filters.adtidy.org/ios/filters/14_optimized.txt ( notice the resemblance? )
Why going the extra mile,loading it from somewhere else,istead of just selecting it from the filter selection ¯\_(ツ)_/¯

**Comment by RouterCFW** [comment]
Was having this issue and thought it was my device 😭

**Comment by fobin** [comment]
> I have updated to beta 5 and it seems like the problem has been resolved. Very nice

Was just going to post the same finding

**Comment by AidanGee7** [comment]
Working for me now too. Closing as this was fixed in beta 5.

**Comment by MPThLee** [comment]
I’m on iPadOS Beta5, And still getting this error. Can anyone reopen this issue?
![IMG_0255](https://github.com/AdguardTeam/AdguardForiOS/assets/26970092/8f87706f-1868-4d59-a78f-483831e55f7b)

**Comment by Rukario** [comment]
Maybe restart the app? I've seen this error once or twice but keep restarting app until it goes away did the trick at least for me.

**Comment by maciboy** [comment]
Updated to Beta 6 and still having the issue!

**Comment by RouterCFW** [comment]
> Updated to Beta 6 and still having the issue!

I disabled dandelion sprout list in annoyances and that fixed it for me

**Comment by maxikuzmin** [comment]
@iJorgen is this still recurring on the latest Beta version? Some users have had the problem disappear with the latest update. I currently have ads blocked in Safari.
@RouterCFW @maciboy @Rukario @MPThLee these are known bugs.
At the moment I have two update states: eternal update with status "Update...", or successful update of all enabled filters within a minute (dandelion sprout list in annoyances has no effect in my case). At the same time "Filter update error" has never appeared for me.
Updating filters in my case occurs after restarting AdGuard, for now it remains to wait for the next beta version, or already the final version, since in September already release iOS 17

**Comment by RouterCFW** [comment]
Just tested 1host pro list on latest dev beta and still get Filter update error , so it’s defiantly just big lists that fail

**Comment by maxikuzmin** [comment]
@RouterCFW any news?

**Comment by AllForLandlord** [comment]
Oh no. Problem reoccurs on beta 8...

**Comment by AllForLandlord** [comment]
@maxikuzmin I couldn't update my filters. It will either be stuck on the infinite update or have an error. Just like the cases mentioned before. :(

**Comment by maxikuzmin** [comment]
@AllForLandlord we will solve this problem in the next update in version 4.6. Please wait

**Comment by AllForLandlord** [comment]
@maxikuzmin Ok thanks!

**Comment by itsmanu35** [comment]
Issue still exists for me on Beta 8. Filters do not refresh (endless loop), I am seeing Ads on Private mode in Safari and also on certain sites in general. Also blank empty space remains on websites in place of ads. 

I feel like it started after I had to deactivate all of the AdGuard toggles in the safari extension menu for a second and after I enabled them again 
![Uploading IMG_8645.jpeg…]()

![IMG_8644](https://github.com/AdguardTeam/AdguardForiOS/assets/144872646/53ab8cc8-a238-4444-b2d9-580e86ef3977)

**Comment by itsmanu35** [comment]
![IMG_8645](https://github.com/AdguardTeam/AdguardForiOS/assets/144872646/44c21a8e-cdba-43fe-b51c-3a17223a5432)

**Comment by AllForLandlord** [comment]
Oh yeah. Adguard is working good on iOS 17 RC! Very happy :D

**Comment by user12334567** [comment]
I have the issue in iOS 17 RC! Filters can not be applied although the toggle is on.

**Comment by AllForLandlord** [comment]
> I have the issue in iOS 17 RC! Filters can not be applied although the toggle is on.

Try to update it. Or try to disable the general toggle and then enable it.

**Comment by itsmanu35** [comment]
still does not work on RC. I even completely wiped my iPhone 12 Pro Max and did not restore from a backup. It is on an endloess loop of "updating content blocker" for the last 15 minutes. Only AdGuard filters enabled

**Comment by maxikuzmin** [comment]
@itsmanu35 as I wrote before, we will fix this issue in version 4.6, please wait
@AllForLandlord on the latest version 17 are your filters updating normally? Could you be more specific about which filters you are using?

**Comment by RevENGE-code** [comment]
I'm on the latest public build of iOS 17`iOS 17.0 (21A329)`. I was unable to activate AG and got an  accompanying error `(SFErrorDomain-Error 3.)`. Disabling `Dandelion Sprout's Annoyances List` solved it for me.

**Comment by AllForLandlord** [comment]
> @itsmanu35 as I wrote before, we will fix this issue in version 4.6, please wait @AllForLandlord on the latest version 17 are your filters updating normally? Could you be more specific about which filters you are using?

The official release of iOS17 is the same as iOS 17 RC. I'm now on RC and things work fine to me.

**Comment by maxikuzmin** [comment]
Since the problem keeps recurring for some users, I'm reopening this issue. 
As a reminder, we will solve the problem of infinite filter updates in a future 4.6 update

**Comment by legendero** [comment]
any update on this guys? when are you expecting version 4.6 to be ready?

Thank you,

**Comment by User202310** [comment]
iOS: 17.0.3 Stable
iPhone 13 Pro Max
AdGuard for iOS 4.5.0 (1002)

**Problem encountered**
ENG: Error updating filters
ITA: Errore nell'aggiornamento dei filtri

The list is not updated and consequently even the advertisements on safari are not blocked.

![IMG_7DC0FAC78377-1](https://github.com/AdguardTeam/AdguardForiOS/assets/147708765/132164c9-703c-46ed-afb7-3a5a26c70f4e)

**Comment by maxikuzmin** [comment]
@User202310 @tadtk @legendero @RevENGE-code @itsmanu35 @AllForLandlord if the problem is still recurring with the latest version of IOS, please upload debug logs the next time the problem recurs and send to email.

Here's what we need you to do:

- Open Settings --> General --> Turn Advanced mode on --> Advanced settings --> Turn Debug logs switch on;
- Reproduce the issue and remember the exact time when it happened;
- Disable "DNS Privacy";
- Open the settings --> Support --> Export logs;
- System popup will be opened --> Choose "Mail" app
- Enter apple@adguard.com as a recipient;
- Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Am4hisa** [comment]
I had the same error (SFErrorDomain 3) on my sode. As many guys have reported, it seems to be an error that occurs when updating a filter that contains many rules. In my case I had the original (not the optimized version) of the AdGuard base filter subscribed to custom filter. I am now using the optimized version to avoid the error. I occasionally encounter ad spaces that are not blocked by the optimized version in adguard base filter, but it almost works fine. I have not encountered any errors when updating the rules.

my status
AdGuard version 4.5.1（1004）
SafariConverterLib v2.0.43
TSUrIFilter v2.1.12
Scriptlets v1.9.37
ExtendedCss v2.0.52
iPhone 15 Pro 256GB iOS 17.0.3
Japanese locale

**Comment by User202310** [comment]
**Disable** AdGuard Base Filter > Update Ok 

**Enable** AdGuard Base Filter > Filter Update Error

![IMG_5082](https://github.com/AdguardTeam/AdguardForiOS/assets/147708765/12274d7a-e456-40cd-b19e-ed3badcfde99)
![IMG_5083](https://github.com/AdguardTeam/AdguardForiOS/assets/147708765/e07853e1-5591-4dd8-a45e-2c7ae0a26f02)

**Comment by User202310** [comment]
> @User202310 @Am4hisa it's strange, some users no longer had this error with the latest iOS updates. Could you also reproduce this and send debug logs as I wrote above?

I have already sent report at apple@adguard.com

Sorry for my bad Eng.

**Comment by AllForLandlord** [comment]
> @tadtk @legendero @RevENGE-code @itsmanu35 @AllForLandlord also please clarify, is the filter update infinite, or does the update finish after some time (3-4 minutes)?

Just tested it and it only took 1min and 14s to finish uploading my filters. I have all of the recommended filters on except for "adguard widgets filter" and I got Chinese filter and adblock warning removal and I don't care about cookies on.
I'm on iOS 17.0.3.

**Comment by fobin** [comment]
I tested this and still get an error if I enable AdGuard Base filter. Logs at that time. I guess UpdateFiltersAsync has the correct error. iPhone 15 Pro Max, iOS 17.0.3.

> 2023/10/16 11:07:53:491 [1059276(AdGuardSDK.ContentBlockerService.updateQueue)]  (ContentBlockerService) - updateContentBlockers; CBs update finished
2023/10/16 11:07:53:491 [1059287(com.apple.expiringTaskExecutionQueue)]  (BackgroundTaskExecutor) - executeAsynchronousTask; Task with reason=SafariProtection.reloadContentBlockers has finished
2023/10/16 11:07:53:491 [1059274(com.apple.expiringTaskExecutionQueue)]  (BackgroundTaskExecutor) - executeAsynchronousTask; Task with reason=SafariProtection+Filters.updateFiltersMetaAndLocalizations has finished
2023/10/16 11:07:53:491 [1058872(AdGuardApp.MainPageModelQueue)]  (MainPageModel) - updateFiltersAsync; Error: Error Domain=SFErrorDomain Code=3 "(null)"
2023/10/16 11:07:53:492 [1058872(AdGuardApp.MainPageModelQueue)]  (UIBackgroundTask) - execute MainPageModel.updateFilters; finished background operation
2023/10/16 11:07:53:501 [217907(com.apple.main-thread)]  (UIBackgroundTask) - execute ChartViewModel.chartStatisticUpdate; start background operation
2023/10/16 11:07:53:505 [217907(com.apple.main-thread)]  (UIBackgroundTask) - execute ChartViewModel.chartStatisticUpdate; finished background operation

**Comment by ameshkov** [comment]
@fobin is it still reproducible now? Could you please enable AdGuard Base filter and then check updates, does the error go away?

**Comment by fobin** [comment]
Now it seems that the error disappears after presenting for 3 seconds. Logs I have still:

```2023/10/16 15:36:23:177 [1277411(AdGuardApp.MainPageModelQueue)]  (MainPageModel) - updateFiltersAsync; Error: Error Domain=SFErrorDomain Code=3 "(null)"```

Link to video showing this: https://share.icloud.com/photos/0c8mOONs6i_WpolWA7J_Xnf6g

![image](https://github.com/AdguardTeam/AdguardForiOS/assets/1096951/c9a0ad01-779d-460c-b41e-117cdef4e0c7)

**Comment by ameshkov** [comment]
```
default	17:32:04.205604+0300	kernel	EXC_RESOURCE -> AdguardBlockingExtensionGeneral[4588] exceeded mem limit: ActiveHard 24 MB (fatal)
default	17:32:04.206007+0300	kernel	memorystatus: killing process 4588 [AdguardBlockingExtensionGeneral] in high band FOREGROUND (100) - memorystatus_available_pages: 62787
```

The problem is that we're hitting the memory limit when trying to load rules into Safari.

This is a peculiar issue. Safari allows up to 150k rules in a single content blocker, but trying to compile just 40k rules breaks it completely.

**Comment by ameshkov** [comment]
What language-specific filter lists do you all have enabled besides AdGuard Base filter?

**Comment by RevENGE-code** [comment]
> @tadtk @legendero @RevENGE-code @itsmanu35 @AllForLandlord also please clarify, is the filter update infinite, or does the update finish after some time (3-4 minutes)?
> 
> 
> 
> 

After disabling `Dandelion Sprout's Annoyances` I no longer get the `SFErrorDomain-Error 3.` And all my lists update without issue. If I now try to reenable that list, it no longer returns `SFErrorDomain-Error 3.`, instead it returns that `an error occurred while updating lists`.

**Comment by ameshkov** [comment]
We have optimized filter lists more aggressively so the problem should be gone if you're using AdGuard filter lists.

But we're still looking into this issue, maybe there will be a better solution.

**Comment by ameshkov** [comment]
@unbeatable-101 rarely used filter rules are removed thus making the final list smaller. We do this for mobile lists for both the performance reasons and to squeeze them into Safari limitations.

**Comment by danieletorelli** [comment]
Hello, keeps happening for big lists (e.g.: OISD big) with iOS 17.0.3 and AdGuard 4.5.0 (1002).

Switching to smaller lists fixes the issue.

**Comment by ameshkov** [comment]
Yeah, and it will be happening for sure. In the next update we will simply trim content blocker size to a certain size just to avoid the complete breakage. This is definitely not an ideal solution. The situation was completely different in iOS 16 and it seems that the change that has broken it is not directly related to Safari content blockers, something has changed with how they process `NSItemProvider` and now it requires much more memory, might've broken many other extensions as well.

We filed a bug report to Apple: FB13282146

**Comment by skypoc** [comment]
I've found a solution.
This is not related to the number of filtering rules. As long as the Adguard basic filter is turned on, the entire Adguard function will fail and an Error is displayed.
Safari Protection👉Turn off the Adguard Base Filter
The problem will be solved.

**Comment by ameshkov** [comment]
@skypoc it actually is related to the number of rules, it's just AdGuard Base filter is the largest one.

**Comment by Idanox** [comment]
I conducted some tests using different filters. In each test, I disabled the "AdGuard Base filter" and the "AdGuard Mobile Ads filter". In the first test, I enabled the "Oisd Small" filter and ran the filter update successfully. In the second test, I did the same with the "HaGeZi Light Blocklist" filter and the update also succeeded. I hope this issue can be resolved without compromising the quality of blocking.

**Comment by Idanox** [comment]
I conducted some tests using different filters. In each test, I disabled the "AdGuard Base filter" and the "AdGuard Mobile Ads filter". In the first test, I enabled the "Oisd Small" filter and ran the filter update successfully. In the second test, I did the same with the "HaGeZi Light Blocklist" filter and the update also succeeded. I hope this issue can be resolved without compromising the quality of blocking.
![IMG_5519](https://github.com/AdguardTeam/AdguardForiOS/assets/36998293/67d7910d-590f-4ddd-9c0d-18dfb20f88cb)

**Comment by Versty** [comment]
@AidanGee7 @Idanox @skypoc @Wrestor @danieletorelli 

Please check if the issue is fixed for you in AdGuard for iOS 4.5.1 version. Already available to download in App Store!

**Comment by User202310** [comment]
> @AidanGee7 @Idanox @skypoc @Wrestor @danieletorelli
> 
> Please check if the issue is fixed for you in AdGuard for iOS 4.5.1 version. Already available to download in App Store!

Great. Problem solved.

**Comment by MariuxReloaded** [comment]
> @AidanGee7 @Idanox @skypoc @Wrestor @danieletorelli
> 
> Please check if the issue is fixed for you in AdGuard for iOS 4.5.1 version. Already available to download in App Store!

I can confirm, too (I'm on iOS 17.1.1 with new AdGuard v4.5.1): problem finally solved! Thank you very much! 🙏

**Comment by Idanox** [comment]
> @AidanGee7 @Idanox @skypoc @Wrestor @danieletorelli
> 
> Please check if the issue is fixed for you in AdGuard for iOS 4.5.1 version. Already available to download in App Store!

Yes, everything works.

**Comment by unbeatable-101** [comment]
I still got a filter update error

**Comment by Wrestor** [comment]
@Versty 
On my end, AdGuard version: `4.5.1(1007)` fixed the [issue](https://github.com/AdguardTeam/AdguardForiOS/issues/2188#issuecomment-1765477652) I encountered. Thanks

**Comment by maxikuzmin** [comment]
@unbeatable-101 did you upgrade to version 4.5.1?

**Comment by unbeatable-101** [comment]
@maxikuzmin yes I did, I've just sent the logs to apple@adguard.com

**Comment by maxikuzmin** [comment]
@unbeatable-101 please try:

- turn off all content blockers in Safari system settings
- reboot the device
- enable content blockers
- enable Safari protection

**Comment by unbeatable-101** [comment]
@maxikuzmin it updated no problem after doing that (other than taking a few minutes)

Thanks!
