### ISSUE TITLE
Intermittent disconnection using DOH3 on Adguard for iOS

### ISSUE THREAD

**Issue by Domsicols** [AdguardTeam/AdguardForiOS#2217]
Been using NextDNS via DOH3 protocol but it seems like adguard always disconnect and the internet is dropping horrendously. Any work around with this problem.

**Comment by ESurina** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Protection";
4. Open the settings --> Support --> **Export logs**;
5. System popup will be opened --> Choose "Mail" app
6. Enter `apple@adguard.com` as a recipient;
7. Mention this issue number in the subject and add the time the issue was reproduced at.

**Comment by Domsicols** [comment]
Will do, Thanks. I have already send an email for this.![image](https://github.com/AdguardTeam/AdguardForiOS/assets/104392824/71bcbd3a-5f55-44a4-9c6c-245fd4a92830)

**Comment by Domsicols** [comment]
![image](https://github.com/AdguardTeam/AdguardForiOS/assets/104392824/e4f9fcae-97ac-43a2-8fa6-68631f2b4067)

**Comment by Domsicols** [comment]
Additional screenshot

**Comment by ESurina** [comment]
Yes, we need logs according to the instructions above.

**Comment by Domsicols** [comment]
I have sent already new logs for this because they want to have a split tunnel mode while using doh3. They needed this because my 1st logs were in full tunnel mode![image](https://github.com/AdguardTeam/AdguardForiOS/assets/104392824/4e5278af-a74e-4bff-9c5d-a881c20d6400)

**Comment by ESurina** [comment]
Also try to use only one network either mobile network or Wi-Fi. 
Do you have a problem only with your Wi-Fi or with any other network?

**Comment by ameshkov** [comment]
Most likely will be resolved when we update DnsLibs to v2.3. The current version uses libcurl and we're not too happy with its HTTP/3 implementation, migrating to a different one.

**Comment by Domsicols** [comment]
Thank youu

**Comment by Domsicols** [comment]
@jslawler this also happen to the current problem when using doh3

**Comment by Domsicols** [comment]
@jslawler when using quic, no promlem. When I checked the the connection time for it, sometimes I see 76hrs connected to it but in the previous state. Quic keeps on disconnecting as well, but I think it was resolved already so no problem with quic now

**Comment by Domsicols** [comment]
The disconnection from DoH3 is more prominent since it randomly drops the connection aside from lockscreen mode.

**Comment by ESurina** [comment]
This problem should be solved when we update DnsLibs to v2.3. You can see the version in logs (state.txt).
If after this the problem appears again, please reopen the issue.

**Comment by Domsicols** [comment]
When will v2.3 be release?

**Comment by Domsicols** [comment]
The problem still persist for me. Running on split tunnel mode
