### ISSUE TITLE
Blocking List Subscription dissapears in testflight v2.0 124

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForiOS#575]
The blocking list subscriptions dissapears and resets itself. The rule counts also dissapear.

### Steps to reproduce

1. Open Aguard Pro
2. Go to blocklist then select a subscription.
4. Open adguard pro then go to dns.
5. Swipe down in the dns settings.
5. Close Adguard Pro
6. Open adguard pro then go to black list.
7. Notice that the blacklist number of rules dissapear
8. Click Check Update
9. Close AdGuard. Open adguard.
10. Blocklist subscription disappears.

Please see attached video.

### Expected behavior

Blocklist subscription should not dissapesr. Rules count should not rest and dissapear aswell.

### Actual behavior

https://vimeo.com/250750840

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Device model and storage size: iPad Pro 10.5
* Operating system and version: 11.2.2
* Browser (e.g. Safari) N/A
* Wi-fi or mobile internet connection: 

Wifi

**Comment by zznosar** [comment]
Can also be recreated via the below steps:

1. Open AdGuard Pro
2. Select a subscription
3. Enable OR Disable Privacy button
4. Close AdGuard
5. Open AdGuard
6. Go to block list
7. Notice that the rules count is gone.
8. Click Check Updates.
9. Close AdGuard
10. Open AdGaurd
11. Go to blocklist. Notice that the subscrioption is gone. Seems like reset / remove.

There is something in ghe DNS Settings / button that actually causes the bug I think. And closing and opening it removes the subscriptions....

**Comment by lancelot-moon** [comment]
> 1. Open Aguard Pro
2. Go to blocklist then select a subscription.
3. Open adguard pro then go to dns.
4. Swipe down in the dns settings.
5. Close Adguard Pro
6. Open adguard pro then go to black list.
7. Notice that the blacklist number of rules dissapear
8. Click Check Update
9. Close AdGuard. Open adguard.
10. Blocklist subscription disappears.

Your step 3 and 4 are superfluous.
Without step 3 and 4, the reproduction steps are the same with mine.

**Comment by zznosar** [comment]
This seems to be fixed in the new beta version 2.0.0 128. The blocklist is still there after performing the above. Will test some more.

**Comment by IvanIin** [comment]
fixed

**Comment by veronikasav** [comment]
@IvanIin 
one of the customers is still facing this issue 

> I have updated to the latest beta via testflight, but am still experiencing this bug of the custom blocklist subscription being deleted every few days. It’s an extremely irritating bug as I have to manually re-add my subscription each time it occurs.

What do you need?
Ticket id: 1748077

**Comment by zznosar** [comment]
@veronikasav , is it possible to get the beta version of the user and also the steps the user did so that we can help the team recreate the issue and test? I am one of the testers who raised the issue and with the current beta version 2.0 128, it’s working fine. Probably there are other steps that will produce this that we missed?

**Comment by veronikasav** [comment]
@zznosar, thank you, will ask.

**Comment by veronikasav** [comment]
Here is the version but we do not have the direct steps 

[smime.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1697800/smime.zip)

**Comment by zznosar** [comment]
@veronikasav apologies but I cannot open the attachment (my mac is treating is a unknown file)... Probably the AdGuard team can check the attached and the version if its 2.0 (128). If my assistance is required (like a retest or something), I'm glad to help.

**Comment by zebrum** [comment]
need to look into it

**Comment by evgeniy-ADG** [comment]
@zebrum please check the log in the CRM, the user ID is 1748077. The customer is reporting the same bug.

**Comment by zznosar** [comment]
If it helps, beta 2.0 (128) and beta 2.0(132) fixed this issue for me... i suggest looking at the users beta version.

The user probably has the older beta 2.0(124) which has this bug. Just my opinion.

**Comment by akmLaVx** [comment]
We've got the same bug on 2.0.132. Will transfer logs in a minute.

**Comment by akmLaVx** [comment]
[2.0.132.zip](https://github.com/AdguardTeam/AdguardForiOS/files/1719390/2.0.132.zip)

**Comment by zznosar** [comment]
@akmLaVx , do you remember the steps you did that leads to the issue? I wanna help and try recreating it. Is it the same as above?

**Comment by zznosar** [comment]
Blocking list in beta 136 is still working for me... will wait for other tester to verify.

**Comment by eccgecko** [comment]
I have been experiencing this on all beta versions of 2.0.0 Unfortunately it’s very hard to know what is causing it, because it seems to be somewhat random. Or at least, you can only tell it’s happened by going in and checking the block list subscriptions yourself - there are no obvious cues that it’s occured.

I had a feeling - but it really was just a feeling, and I have no concrete proof - that it may have had something to do with enabling Flight Mode. It seemed to occur more often if I had eneabled Flight Mode in the previous 24 hours, but again I can’t be sure (it’s not like it would occur everytime I enabled Flight Mode).

Having said all this, it seems to not be occuring anymore on the latest 2.0.0 140 beta, but I will keep an eye on it and reprt here if it happens again.

**Comment by ameshkov** [comment]
Plz reopen if it happens again

**Comment by eccgecko** [comment]
Guess I spoke too soon. Unfortunately it has happened again today, on both iPhone and iPad, at different times in the day. Both are using latest version of the 2.0 beta (140).

Like I said before, it's very hard to know what is causing this. As far as I can tell, it occurs pretty much randomly. Finding out its causes isn't made easier by the fact that the only reliable way for me to find out of it's occurred is to keep opening the app manually and checking to see if the subscription has disappeared or not. Obviously that gets tiresome, and it's not like I go and check after every single action I take on my devices.

I do turn Flight Mode on on both devices most nights, so am not sure if this has something to do with it. Like I said, it's not like it occurs every time I use flight mode (I always check after disabling Flight Mode). I also use the OpenVPN connect app to connect to personal and work VPNs, but these are used sporadically on these devices. When I disconnect from the OpenVPN connection, I usually go into settings and reconnect to the AdGuard Pro VPN. I'm not sure if this has anything to do with the bug either, but I thought it might be useful to know (again, it's not like, every time I do this, the subscription is disappearing).

I'm sorry I can't give you more concrete steps to reproduce this. It had seemed this was fixed in 140, as it certainly seemed like the longest time had lapsed before it reoccured.

**Comment by polarimetric** [comment]
I’m experiencing the exact same thing as @eccgecko: without fail, after a few days of usage, my DNS blocking list subscriptions disappear and I have to re-add them. The only way I notice is that ads start appearing in non-Safari View Controller apps like Facebook again. I’ve attempted the steps to reproduce in the original post here and they do NOT trigger the bug, so it seems that there is some unrelated issue which is still causing the subscriptions to randomly disappear.

It may have something to do with having the VPN disabled for some period of time and then re-enabling it—something about iOS background app refresh?

**Comment by zznosar** [comment]
@eccgecko @polarimetric are both of you using host files from raw.githubusercontent? Or are you using the default ones provided by AdGuard? There is also a new update 2.0.2. Can you check if it still occurs?

**Comment by polarimetric** [comment]
I've done both (used githubusercontent files and AdGuard's suggested defaults), and this appears to be fixed in 2.0.2. I have not yet experienced the bug since installing the latest TestFlight beta.
