### ISSUE TITLE
Change the way how trackers detection displayed in DNS log

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForiOS#656]
1. Change the color in DNS log from bright red to yellow.

2. On 'Request Detail' screen put 'service information' block right after 'properties'

3. Add this format to detected trackers: `dd/mm/yyyy, hh:mm:ss, Tracker detected - Name`

4. Sometimes there is no  'service information' block on 'Request Detail' screen - it's probably a bug.

**Comment by lancelot-moon** [comment]
The 1st, 3rd and 4th point was reported by me.

Yes, most users don't know the now bright red in log is for trackers and analytics.
It's good that you note them as trackers or analytics in log with words.

Thank AdGuard team for the great decision and hard working!

**Comment by Sailor-Chibimoon** [comment]
@lancelot-moon you are very persistent with the dull white colour. I thought you want AdGuard to decide the right colour. Let them be and don’t be persistent in the dull white.

I been reading and following the repo, preventing my self from replying, but you’re very impatient and persistent.

I read that two tester already provided their opinion on night shift and dull white and you still push what you want.

I’m the third person, that will say, that if they put dull white, it will not be visible. I have iphone 7 plus and iphone x. My screen is warmer yellow so the dull white will not appear correctly. I use true tone and night shift to protect my eyes. I am one of the general users who use it. 

Your screen probably has bluer tint that’s why you are very persistent with dull white and you dont use night shift at all.

You need to be considerate with others and also don’t be too demanding.

I saw that you raised two issues number with the same bug. You already know that there is an existing bug and issue you created and you still created a new one. Plus you’ve been bugging the team with bug report emails with same issue. You probably didn’t know that adguard is supporting multiplt platforms. If you keep on raising emails with same issue, it will impact their sla’s and also impact those people who require genuine help because the team will focus on your repeated and annoying email.

I know, i am annoying to you, but i am confident and sure that you are annoying to the AdGuard Team.

Probably the reason why their team lead is not active anymore. Always mentioning his name in your request.

You’re probably good in translating, but i dont think you have the qualities of a good tester. Don’t confuse selfishness with testing. Don’t confuse being direct to being forceful. Don’t confuse opinion with whining.

I’m serious here. And not the jolly old me. I want you to realise what is lacking with you.

Compare all the issues you raised with issues raised with other people. Hopefully you can see the difference.

Peace out. 

You probably just stick translating and stop testing. And please don’t tell me that you do this as a volunteer to make adguard app better for people. Because I am one of those “people” and the general census, and I am not amuse and thirll with what you are contributing. All i see is whining and discontent. No appreciation of the current situation.

**Comment by lancelot-moon** [comment]
> Your screen probably has bluer tint that’s why you are very persistent with dull white and you dont use night shift at all.

Stop approaching me and your any unreal indictment.
I never see that you have so many opinions to other people.

I actually enabled ‘Night Shift’ for the experiment on my iPhone.
My screen also became warmer yellow.
Under ‘Night Shift’, the screen becomes warmer yellow.
Why should I need dull white to be correctly shown under ‘Night Shift’?
Under ‘Night Shift’, it's enough as long as dull red, dull yellow, dull green and dull white are clear distinguished in the black background.

Since it's not problem under ‘Night Shift’, we should consider for the users who don't use ‘Night Shift’.
Not everyone likes warmer yellow screen so they don't enable  ‘Night Shift’.
However, words with bright colors let eyes be easy tired and uncomfortable.
Don't only think of yourself.
According to your logic, you should also blame AdGuard team since they originally use dull red and dull green in the now log because bright colors are justice in your opinion.
But you're always and only aimed at me.
You have annoyed me.
You even tracked me so I had blocked you.
Leave me alone!

I believe that AdGuard team also did the experiment by themselves and then made the decision.
You guys, oppose due to opposition and intentionally ignore this.
Actually, you don't trust AdGuard team and their decisions.

You really make troubles here.

**Comment by Sailor-Chibimoon** [comment]
Sailor Lancelot-Moon, so because other people gave their opinion which is different from you, now, you are mad at them? Mad at us? Is that it? Is that how you work? Is that how you accept criticism? Is that how you accept opinion? 

Poor them. The people helping in the beta test. They are here to do testing and provide feedback yet you become mad at them because you dont want to accept their opinion.

I don’t know them, but hopefully, they will still be loyal to AdGuard even though a “tester” like you is here not to test but to whine and to not accept people’s thought.

Sending bug report which contains same bug is not helpful to them. It’s called spamming.

Yeah probably i only reply to you here but i reply to other people too in reddit or macrumors... why I reply to you is because your uniqueness which set you apart from others.

**Comment by lancelot-moon** [comment]
You just don't understand your mistakes.
Take away your self-righteous justice.

You continue to intentionally ignore that ameshkov self-assigned my that request.
You don't respect AdGuard team and testers at all.
Sailor Lancelot-Moon?
You never know to respect people.
Simply a trouble maker.

I won't reply you anymore.
Do you wish ameshkov to delete your posts again?

Thank AdGuard team.
We work hard to let AdGuard Pro v2.0.0 be better.
However, someone is constantly aimed at me.
Disgusting enough.

**Comment by Sailor-Chibimoon** [comment]
Ohh wow. 😂😁😊 you use the trump card again of calling the team lead... owww

I respect testers! Yes. every one here in this repo that - even the busiest time of their lives they have time to help and raise the *helpful* issues and stuffs. Instead of whines and commands from you.

Respect is earned not imposed. With your attitude, you don’t deserve it...

**Comment by lancelot-moon** [comment]
Everyone knows that someone intentionally tests my nerve and patience.

ameshkov:
@Sailor-Chibimoon

Stop that please.

He never respects anyone here.
May AdGuard administrator block someone in the blacklist for forbiding him to visit AdGuard GitHub since he doesn't know to stop his harassment?

Thanks.

**Comment by Sailor-Chibimoon** [comment]
I’m a she not a he. A girl not a boy. Why do you always say that I am a he. Do i look and sound like a boy to you? 😂😂😊😊😫😫😫 i’m a girl not yet a woman.

**Comment by Sailor-Chibimoon** [comment]
Wait until i have my delivery next month Sailot @lancelot-moon.  your cute name is cute. I hope that my son will not have a bad attitude like you....

**Comment by zebrum** [comment]
if tracker was blocked, should we change the info to smthg like this: `dd/mm/yyyy, hh:mm:ss, Tracker blocked - Name`

**Comment by lancelot-moon** [comment]
I remember that AdGuard doesn't block trackers and analytics from Disconnect database.
We'll meet a problem.
The problem is my 1st question in my another post.
But nobody answers it...
Well, I wish answers for the 1st and 2nd questions.
https://github.com/AdguardTeam/AdguardForiOS/issues/606#issuecomment-359168460

1. I didn't use AdGuard DNS server and only used AdGuard SDN filter as the subscription at that time.
There is the rule, ||voicefive.com^, in AdGuard SDN filter.
It's strange that sb. voicefive.com wasn't blocked, only processed.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/cB7xwTh.png)
</details><br/>

Is the priority of trackers database higher than ad filters?
How will AdGuard Pro deal with when a domain is in an ad filter and trackers database at the same time?
Detected or blocked?

**Comment by zznosar** [comment]
I’ve checked. Regular yellow is visible and looks good in my screeen. No issues with my night shift and true tone.

<img width="1112" alt="image 4" src="https://user-images.githubusercontent.com/27464836/36331253-2fe4a276-13c1-11e8-84d5-474fc43b036e.png">

**Comment by lancelot-moon** [comment]
@ameshkov 

Sir,

May you give this kind of yellow (Hex Code #RRGGBB: #FFFF00)?
https://www.rapidtables.com/web/color/RGB_Color.html

This under yellow is the example.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/Nd30JWB.png)
</details><br/>

The now yellow color which you use in DNS Requests Log lets me think about yellow clay.
Honestly, it's **Not Beautiful** according to my Aesthetic. ｡･ﾟ･(ﾉД`)ヽ(ﾟДﾟ )秀秀

**Comment by Sailor-Chibimoon** [comment]
Your definition of beautiful is not the samr as others point of view. Don’t force what you want. They already decided the color so stop complaining and tagging thr AdGuard Team Lead. Leave them alone.

**Comment by Sailor-Chibimoon** [comment]
Guys, save your time and effort talking to Sailor @lancelot-moon. He does not care about others opinion. He only cares about what he wants. He’s like a spoiled girl that always complains and whines. Don’t work with him if you want to hve a peaceful life. I urge AdGuard team to revoke his beta testing license. Just stay translating. That’s it. Stop the nosense petty testing. Let the intelligent people do the test.

I saw one tester want to reconcile with this guy??? Why! OMG! He does not deserve an apology as this person is the one causing troubles anyway. Always. To the users and testers to this repo, i warn you. Don’t work with him.

He does not know those techy stuffs that you are talking about. Other testers should beware of him. Very sexist and egoistic. No wonder AdGuard Team Lead is very quiet this days. All of the notifications comes from this guy that are not really important.

Everyday, this user always tag him or any adguard developer of any issues or post he makes.. He always want special attention. No wonder why no body likes him.... i can predict that tomorrow or later he will tag them again... he is a dark sailor soldier.

To AdGuard Team, I suggest go to reddit or macrumors and ask people of what they really want. You will know what REAL USERS want. What he wants is not the representation of what the General Users wants. Please don’t always delet my post. He needs to learn the hard way. I used to like him but i am starting to hate him with his attitude.

**Comment by Sailor-Chibimoon** [comment]
I urge everyone, all the testers, that includes public beta testers, and the AdGuard Team, Do not work or coordinate or in anyway interact with Sailor @lancelet-moon. I will not mention the testers as they are too many. He should stop being rude to everyone, accept opinion of others and stop being bossy. He should accept the fact that what he wants is not what GENERAL Users wants. Please check twitter, reddit, macrumors and 9to5mac, everyone is waiting for AdGuard PRO 2.0. He is the one delaying the release of AdGuard PRO 2.0. That means the fix for "Error Loading in Safari" will be delayed as well. DNSCrypt which is all about security will be delayed as well. General Users have been waiting for the fixes and new features, but THANKS to @lancelot-moon, they will all be delayed because he is forcing the AdGuard Team to delay and stop the release. 
It’s impacting so many people including users here in Canada.

I am not being rude here. I am just stating facts. Check the issues he raised and the interactions he have with the people and tester. You, guys,  will know what I mean. He needs to learn. Being good to him does not work, so an iron fist approach should teach him.

**Comment by lancelot-moon** [comment]
I think that AdGuard team should employ me with a formal and high level position, otherwise I really don't know that I'm a so great man or senior executive who can affect the policy of AdGuard team.

According to someone's logic from his tofu brain, all bugs of AG Pro v2.0.0 are my mistakes.

I also like Japanese anime.
Usually, such guy like someone is an evil role / a bad man in stories.
Moon will punish the guy.

Forgive for my poor humor if it's not amusing.
I'm really not humorous enough.
I need to close the border and then practice more jokes.
Well, AdGuard administrator is enjoying his weekend.
We can't ask him work overtime.
So someone can constantly make trouble here.

**Comment by Sailor-Chibimoon** [comment]
If I read it correctly, it says “Current Beta” in the tag, which means it’s fixed in the 2.0. Probably the fixed has been there since January, But since you always want your changes to be included in 2.0, you always says to wait even to other testers. I aimed at you because out of all the issues and interactions here in this repo with other people, You are the only person who constantly says 2.0 should be delayed. Read the forums and see how many people are waiting for the fixes and the fix is in 2.0, that you constantly want to delay.

**Comment by lancelot-moon** [comment]
v2.0.0 is still not released yet.
It only has beta versions, no release version.

Someone always forces AdGuard team to release an irresponsible product on the market.
For instance, a company doesn't need QA (we testers are AdGuard's Quality Assurance although we are volunteers) because users on the market are my QA. XDD
I start to believe that someone is a spy from AdBlock by Future Mind.

According to the original plan, Web Reporting tool is in v2.0.0.
Is Web Reporting tool ready?
Is the localization of Web Reporting tool online?

Is the new page which introduces subscriptions ready?

Are those other bugs solved even if not including the critical & small bugs which I reported and my feature requests?

Someone should shut up!

In fact, I really know why AdGuard Pro v2.0.0 is still not released yet.
It's because that someone who loves Sailor Moon didn't pay the fee of working overtime to AdGuard team.
Someone is indeed the chief offender who delayed the release time of AdGuard Pro v2.0.0.

Forgive for my cold jokes.
I'm not humorous enough.
If other people who are reading the articles can give me knowing smiles, I'll appreciate.

**Comment by Sailor-Chibimoon** [comment]
I wonder who is the Chief Offender here of the delay, i am 100% sure that it’s you Sailor @lancelot-moon . Anyway, it’s already very late here in Vancouver. I wish that tomorrow, i will see *good* things and not whines and complains and delay requests from someone. It’s very tiring if this sailor soldier still does not know what he is lacking. Maybe I will apply for a beta test. And see if your *conclusions* are correct. 

Yes. Probably i am from Future Mind. But isn’t it you who is steals ideas from Future Mind? With all that swiches and stuffs. Those are from Adblock! And you want AdAgurd to be a pirated copy of AdBlock, with all of your requests.

**Comment by lancelot-moon** [comment]
The selection of filters are early applied in other platforms of AdGuard. I just think it's necessary to realize the feature in iOS version. AdGuard doesn't learn AdBlock. Someone insults not only me but also AdGuard. Obviously, someone only knows AdBlock and is unfamiliar with AdGuard products. A spy from AdBlock constantly makes trouble here. Someone should get out back to AdBlock. Live and watch Sailor Moon in himself world.

**Comment by Sailor-Chibimoon** [comment]
Sad. My comments are deleted again. To @lancelot-moon, you really don’t understand and never learn. You mentioned the adguard team lead again and complain and whine. There is a difference between reprimand and harrass. Mine is a reprimand. Check your attitude. I already sounded like your mother but you still did not understand. I give up and will probably leave Adguard all together because of you with your falsely accusations. It’s tiring and my jolly attitude cant cope. As an advice, be like the other testers. Stop the whining and complain. No testers here complain and whine like you. That is your weakness and your indiference.

Bye for now! Hopefully, my future baby Lance Zelot Moon will not have attitude problems like you.

**Comment by ameshkov** [comment]
Got it, pure trolling and nothing contributed. Blocked.
