### ISSUE TITLE
Crash after adding custom filter

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#843]
### Steps to reproduce

1. Go to Filters -> Custom 
2. Add a filter

Adguard stopped.
# 
https://uploads.adguard.com/IMG_5578.TRIM.MOV

### Your environment

* Adguard 2.5.0 (110)
* Operating system and version: (ios 12.1)

**Comment by IvanIin** [comment]
@aspasskaya  I have fixed this crash, but you should enter the filter url instead of a rule

**Comment by Superkloton** [comment]
@Ivanlin no it happens for user filters as well.

**Comment by Superkloton** [comment]
@IvanIin AdGuard still crashes in Beta 134 when adding new user filters (not custom filters).

**Comment by ameshkov** [comment]
@Superkloton I created a new bug for that:
https://github.com/AdguardTeam/AdguardForiOS/issues/1013

Please specify your device and iOS version there.
