### ISSUE TITLE
Links are mixed up in About and User Filter sections

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForiOS#851]
### Steps to reproduce
! iPhone Language - English
1. Go to User Filter section
2. Go to About section

### Expected behavior
User Filter
- note about rule syntax -> https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters
# 
About
- Site  -> https://adguard.com/en/welcome.html
- Forum  -> https://forum.adguard.com/index.php#english-forums.47
- Acknowledgments -> https://kb.adguard.com/en/miscellaneous/acknowledgments
- More -> http://agrd.io/ios_adguard_products

### Actual behavior
User Filter
- note about rule syntax -> https://kb.adguard.com/en/ios/features
# 
About
- Site  -> gitthub - https://github.com/AdguardTeam/AdguardForiOS
- Forum  -> site - https://adguard.com/en/welcome.html?aid=28180
- Acknowledgments -> report an issues - https://github.com/AdguardTeam/AdguardForiOS/wiki/How-to-report-a-bug
- More -> site - https://adguard.com/ru/welcome.html?aid=28180

### Your environment

* Adguard 2.5.0 (110)
* Operating system and version: (ios 12.1)

**Comment by zzebrum** [comment]
Thanks link should lead to [acknowledgments](https://kb.adguard.com/en/miscellaneous/acknowledgments)?

**Comment by zzebrum** [comment]
More -> http://agrd.io/ios_adguard_products 
The question is do we still need it to lead to iOS Pro product page now?

**Comment by zzebrum** [comment]
I mean there is no difference between Site and More links

**Comment by aspasskaya** [comment]
v3.0.0 (118)
### Section 'About' -> Forum link
**Should be opened English Forum:**

(only ios 12, iphone X) Settings: Region -> Japan, Language -> English   
#### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/54914168-6043d600-4f05-11e9-802d-ee05bc85e840.png)
### Section 'User filter'
**Should be opened "How to create your own ad filters"**
#### Actual behavior
![image](https://user-images.githubusercontent.com/43952607/54914560-49ea4a00-4f06-11e9-9046-b219838f5ffe.png)

**Comment by IvanIin** [comment]
fixed in 123

**Comment by aspasskaya** [comment]
The problem is still exist:
- In section User Filter opened features -> should be opened "How to create your own ad filters"
- In section About Acknowledgments opened in English, when the others opened in Russian.

**Comment by IvanIin** [comment]
fixed in 130
