### ISSUE TITLE
Filters tags disappeared

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForiOS#911]
v3.0.0(117)

**Comment by IvanIin** [comment]
Fixed in 118.
This is app update error. The bug should not be reproduced with a clean installation of the application or when upgrading from the appstore version(101) to 118 and higher.

**Comment by aspasskaya** [comment]
The problem is still exist.
![image](https://user-images.githubusercontent.com/43952607/57787674-808e5500-773e-11e9-8911-0e7ca085fc90.png)

**Comment by ameshkov** [comment]
Cannot reproduce with .134
